### ISSUE TITLE
UIFrame中Release函数，迭代器修改了自己

### ISSUE THREAD

**Issue by morganfreemanX** [feifeid47/Unity-Async-UIFrame#7]
UIFrame中Release函数，迭代器修改了自己

/// <summary>
        /// 强制释放已经关闭的UI，即使UI的AutoDestroy为false，仍然释放该资源
        /// </summary>
        public static void Release()
        {
            foreach (var item in instances)
            {
                if (item.Value != null && !item.Value.activeInHierarchy)
                {
                    UIFrame.Destroy(item.Value);
                    OnAssetRelease?.Invoke(item.Key);
                    instances.Remove(item.Key);
                }
            }
        }

**Comment by feifeid47** [comment]
感谢反馈
