### ISSUE TITLE
子UI打开会产生父UI之外的UI实例化Gameobject，是否有不新增实例子UI的方法。

### ISSUE THREAD

**Issue by morganfreemanX** [feifeid47/Unity-Async-UIFrame#8]
private void UpdateSelect()
        {
            this.btnSign.ToggleActive(this.mSelectIndex == 0);
            this.btnDailyTask.ToggleActive(this.mSelectIndex == 1);
            this.btnWeekTask.ToggleActive(this.mSelectIndex == 2);
            this.btnAchievement.ToggleActive(this.mSelectIndex == 3);

            for (int i = 0; i < this.Children.Count; i++)
            {
                if (i == this.mSelectIndex)
                {
                    UIFrame.Show(this.Children[i]);
                }
                else
                {
                    UIFrame.Hide(this.Children[i]);
                }
            }
        }

**Comment by feifeid47** [comment]
没太理解你的描述，能描述的更加详细点吗，方便把你复现问题的Unity工程（或新建一个简单的工程能够复现你所遇到的问题）打包发到。feifeid47@qq.com里吗。

**Comment by feifeid47** [comment]
没太理解你的描述，能描述的更加详细点吗，方便把你复现问题的Unity工程（或新建一个简单的工程能够复现你所遇到的问题）打包发到。feifeid47@qq.com里吗。

**Comment by morganfreemanX** [comment]
子UI类不要使用标签
